apiVersion: v1
kind: Service
metadata:
  name: usuarios-db
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: usuarios-db
  sessionAffinity: None
  type: ClusterIP
